apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinigram
  namespace: default
  labels:
    app: infinigram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinigram
  template:
    metadata:
      labels:
        app: infinigram
    spec:
      containers:
      - name: infinigram
        image: gcr.io/consus-394000/ashish/infinigram:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_PORT
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: FLASK_PORT
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MODE
        - name: MAX_QUERY_CHARS
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_QUERY_CHARS
        - name: MAX_QUERY_TOKENS
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_QUERY_TOKENS
        - name: MAX_CLAUSES_PER_CNF
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_CLAUSES_PER_CNF
        - name: MAX_TERMS_PER_CLAUSE
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_TERMS_PER_CLAUSE
        - name: MAX_SUPPORT
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_SUPPORT
        - name: MAX_CLAUSE_FREQ
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_CLAUSE_FREQ
        - name: MAX_DIFF_TOKENS
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_DIFF_TOKENS
        - name: MAXNUM
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAXNUM
        - name: MAX_DISP_LEN
          valueFrom:
            configMapKeyRef:
              name: infinigram-config
              key: MAX_DISP_LEN
        volumeMounts:
        - name: index-data
          mountPath: /data
        - name: config-volume
          mountPath: /app/api_config.json
          subPath: api_config.json
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: index-data
        persistentVolumeClaim:
          claimName: infinigram-index-pvc
      - name: config-volume
        configMap:
          name: infinigram-config 