apiVersion: batch/v1
kind: Job
metadata:
  name: infinigram-index
  namespace: ashish
spec:
  backoffLimit: 50
  completions: 64
  parallelism: 64
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      containers:
      - name: indexing-worker
        image: gcr.io/consus-394000/ashish/infinigram:latest
        command: ["python3"]
        args: ["/scripts/indexing_worker.py"]
        
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEBUG
          value: "true"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token-secret
              key: token
        resources:
          requests:
            memory: "500Gi"    # Increased for indexing workload
            cpu: "70"
            ephemeral-storage: "800Gi"  # Increased storage request
        volumeMounts:
        - name: gcp-credentials
          mountPath: /gcp-credentials
          readOnly: true
        - name: temp-volume
          mountPath: /tmp
        - name: indexing-script
          mountPath: /scripts
          readOnly: true
      
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-service-account-secret
      - name: temp-volume
        emptyDir: {}
      - name: indexing-script
        configMap:
          name: indexing-worker-script
          defaultMode: 0755 