apiVersion: batch/v1
kind: Job
metadata:
  name: infinigram-merge
  namespace: ashish
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: merge-worker
        image: gcr.io/consus-394000/ashish/infinigram:latest
        command: ["python3"]
        args: ["/scripts/merge_worker.py"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/gcp-credentials/service-account.json"
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEBUG
          value: "true"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token-secret
              key: token
        resources:
          requests:
            memory: "500Gi"    # Increased for indexing workload
            cpu: "70"
            ephemeral-storage: "800Gi"  # Increased storage request
        volumeMounts:
        - name: gcp-credentials
          mountPath: /gcp-credentials
          readOnly: true
        - name: temp-volume
          mountPath: /tmp
        - name: merge-worker-script
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-service-account-secret
      - name: temp-volume
        emptyDir: {}
      - name: merge-worker-script
        configMap:
          name: merge-worker-script
          defaultMode: 0755