apiVersion: v1
kind: Service
metadata:
  name: infinigram-service
  namespace: default
  labels:
    app: infinigram
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: infinigram