name: infini-gram-i
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11.8 # needs >=3.9 because ai2-olmo calls functools.cache, but <3.12 because ai2-olmo depends on torch>=2.0,<2.2 but python 3.12 only supports torch>=2.2
  - pip:
    - transformers==4.36.1
    - tokenizers==0.15.0
    - flask
    # - protobuf==3.20.3 # install separately
    # - ai2-olmo==0.2.4 # install separately
  - sentencepiece=0.1.96 # install separately
  - numpy
